routes/web.php
<?php

use App\Models\Index;

//Route::redirect('/admin', '/login');
Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }
    return redirect()->route('admin.home');
});

Auth::routes(["register" => false]);

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/index', 'SettingsController@index_edit')->name('settings.index');
    Route::put('/index', 'SettingsController@index_update')->name('settings.index.update');

    Route::get('/mails', 'MailController@index')->name('mail.index');
    Route::get('/mails/{receivedMail}', 'MailController@show')->name('mail.show');

    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Crm Status
    Route::delete('crm-statuses/destroy', 'CrmStatusController@massDestroy')->name('crm-statuses.massDestroy');
    Route::resource('crm-statuses', 'CrmStatusController');

    // Crm Customer
    Route::delete('crm-customers/destroy', 'CrmCustomerController@massDestroy')->name('crm-customers.massDestroy');
    Route::resource('crm-customers', 'CrmCustomerController');

    // Crm Note
    Route::delete('crm-notes/destroy', 'CrmNoteController@massDestroy')->name('crm-notes.massDestroy');
    Route::resource('crm-notes', 'CrmNoteController');

    // Crm Document
    Route::delete('crm-documents/destroy', 'CrmDocumentController@massDestroy')->name('crm-documents.massDestroy');
    Route::post('crm-documents/media', 'CrmDocumentController@storeMedia')->name('crm-documents.storeMedia');
    Route::post('crm-documents/ckmedia', 'CrmDocumentController@storeCKEditorImages')->name('crm-documents.storeCKEditorImages');
    Route::resource('crm-documents', 'CrmDocumentController');

    // Kindergarden Branch
    Route::delete('kindergarden-branches/destroy', 'KindergardenBranchController@massDestroy')->name('kindergarden-branches.massDestroy');
    Route::resource('kindergarden-branches', 'KindergardenBranchController');

    // Kindergarden Group
    Route::delete('kindergarden-groups/destroy', 'KindergardenGroupController@massDestroy')->name('kindergarden-groups.massDestroy');
    Route::resource('kindergarden-groups', 'KindergardenGroupController');

    // Kid
    Route::post('/exportKids', 'KidController@export')->name('exportKids');
    Route::post('/exportKidsByGroup', 'KidController@exportKidsByGroup')->name('exportKidsByGroup');
    Route::delete('kids/destroy', 'KidController@massDestroy')->name('kids.massDestroy');
    Route::resource('kids', 'KidController');
    // Parent Guardian
    Route::delete('parent-guardians/destroy', 'ParentGuardianController@massDestroy')->name('parent-guardians.massDestroy');
    Route::resource('parent-guardians', 'ParentGuardianController');
    Route::resource('kid-categories', 'kidCategoriesController');
});
Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
    // Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
        Route::post('profile', 'ChangePasswordController@updateProfile')->name('password.updateProfile');
        Route::post('profile/destroy', 'ChangePasswordController@destroy')->name('password.destroyProfile');
    }
});
Route::middleware(['web'])->group(function () {
    Route::get('/', function () {
        return view('front.layouts.main');
    });
    Route::get('/home', function(){
        $index = Index::first();
        return view('front.home', compact('index'));
    });
    Route::get('/register', function(){
        return view('front.pages.register');
    });
    Route::get('/contact', function(){
        return view('front.pages.contact');
    });
    Route::get('/about', function(){
        return view('front.pages.about');
    });
    Route::get('/check-if-registered', function(){
        return view('front.pages.checkIfResgistered');
    });
    Route::post('/register', 'Front\RegisterController@register')->name('register');
    Route::post('/getBranches', 'Front\RegisterController@getBranches')->name('getBranches');
    Route::post('/getKidCategories', 'Front\RegisterController@getKidCategories')->name('getKidCategories');
    Route::post('/getKidNationalities', 'Front\RegisterController@getKidNationalities')->name('getKidNationalities');
    Route::post('/getBranchGroups', 'Front\RegisterController@getBranchGroups')->name('getBranchGroups');
    Route::post('/checking-if-registered', 'Front\RegisterController@checkIfRegistered')->name('checkIfRegistered');
    Route::post('/get-branches', 'Front\RegisterController@retrieveBranchesWithGroups')->name('retrieveBranchesWithGroups');

    Route::post('/contect', 'ContactFormController@send')->name('contact.send');
});

app/Models/KindergardenBranch.php
<?php

namespace App\Models;

use \DateTimeInterface;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class KindergardenBranch extends Model
{
    use SoftDeletes;
    use HasFactory;

    public $table = 'kindergarden_branches';

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'name',
        'address',
        'branch_manager',
        'email',
        'phone',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    public function kindergardenBranchKindergardenGroups()
    {
        return $this->hasMany(KindergardenGroup::class, 'kindergarden_branch_id', 'id');
    }

    public function branchKids()
    {
        return $this->hasMany(Kid::class, 'branch_id', 'id');
    }

    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }
}

app/Http/Controllers/Admin/KindergardenBranchController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyKindergardenBranchRequest;
use App\Http\Requests\StoreKindergardenBranchRequest;
use App\Http\Requests\UpdateKindergardenBranchRequest;
use App\Models\KindergardenBranch;
use App\Models\KindergardenGroup;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class KindergardenBranchController extends Controller
{
    public function index()
    {
        abort_if(Gate::denies('kindergarden_branch_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $kindergardenBranches = KindergardenBranch::all();

        return view('admin.kindergardenBranches.index', compact('kindergardenBranches'));
    }

    public function create()
    {
        abort_if(Gate::denies('kindergarden_branch_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.kindergardenBranches.create');
    }

    public function store(StoreKindergardenBranchRequest $request)
    {
        $kindergardenBranch = KindergardenBranch::create($request->all());
        KindergardenGroup::upsert([
            ['name' => '2-3', 'vacancy' => 0, 'kindergarden_branch_id' => $kindergardenBranch->id],
            ['name' => '3-4', 'vacancy' => 0, 'kindergarden_branch_id' => $kindergardenBranch->id],
            ['name' => '4-5', 'vacancy' => 0, 'kindergarden_branch_id' => $kindergardenBranch->id],
            ['name' => '5-6', 'vacancy' => 0, 'kindergarden_branch_id' => $kindergardenBranch->id]
        ], ['name', 'vacancy', 'kindergarden_branch_id']);

        return redirect()->route('admin.kindergarden-branches.index');
    }

    public function edit(KindergardenBranch $kindergardenBranch)
    {
        abort_if(Gate::denies('kindergarden_branch_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.kindergardenBranches.edit', compact('kindergardenBranch'));
    }

    public function update(UpdateKindergardenBranchRequest $request, KindergardenBranch $kindergardenBranch)
    {
        $kindergardenBranch->update($request->all());

        return redirect()->route('admin.kindergarden-branches.index');
    }

    public function show(KindergardenBranch $kindergardenBranch)
    {
        abort_if(Gate::denies('kindergarden_branch_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $kindergardenBranch->load('kindergardenBranchKindergardenGroups', 'branchKids');

        return view('admin.kindergardenBranches.show', compact('kindergardenBranch'));
    }

    public function destroy(KindergardenBranch $kindergardenBranch)
    {
        abort_if(Gate::denies('kindergarden_branch_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $kindergardenBranch->delete();

        return back();
    }

    public function massDestroy(MassDestroyKindergardenBranchRequest $request)
    {
        KindergardenBranch::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

resources/views/admin/kindergardenBranches/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.kindergardenBranch.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.kindergarden-branches.store") }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label class="required" for="name">{{ trans('cruds.kindergardenBranch.fields.name') }}</label>
                <input class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" type="text" name="name" id="name" value="{{ old('name', '') }}" required>
                @if($errors->has('name'))
                    <div class="invalid-feedback">
                        {{ $errors->first('name') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.kindergardenBranch.fields.name_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="address">{{ trans('cruds.kindergardenBranch.fields.address') }}</label>
                <input class="form-control {{ $errors->has('address') ? 'is-invalid' : '' }}" type="text" name="address" id="address" value="{{ old('address', '') }}" required>
                @if($errors->has('address'))
                    <div class="invalid-feedback">
                        {{ $errors->first('address') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.kindergardenBranch.fields.address_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="branch_manager">{{ trans('cruds.kindergardenBranch.fields.branch_manager') }}</label>
                <input class="form-control {{ $errors->has('branch_manager') ? 'is-invalid' : '' }}" type="text" name="branch_manager" id="branch_manager" value="{{ old('branch_manager', '') }}" required>
                @if($errors->has('branch_manager'))
                    <div class="invalid-feedback">
                        {{ $errors->first('branch_manager') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.kindergardenBranch.fields.branch_manager_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="email">{{ trans('cruds.kindergardenBranch.fields.email') }}</label>
                <input class="form-control {{ $errors->has('email') ? 'is-invalid' : '' }}" type="email" name="email" id="email" value="{{ old('email', '') }}">
                @if($errors->has('email'))
                    <div class="invalid-feedback">
                        {{ $errors->first('email') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.kindergardenBranch.fields.email_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="phone">{{ trans('cruds.kindergardenBranch.fields.phone') }}</label>
                <input class="form-control {{ $errors->has('phone') ? 'is-invalid' : '' }}" type="number" name="phone" id="phone" value="{{ old('phone', '') }}" step="1">
                @if($errors->has('phone'))
                    <div class="invalid-feedback">
                        {{ $errors->first('phone') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.kindergardenBranch.fields.phone_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/kindergardenBranches/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('cruds.kindergardenBranch.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.kindergarden-branches.update", [$kindergardenBranch->id]) }}" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label class="required" for="name">{{ trans('cruds.kindergardenBranch.fields.name') }}</label>
                <input class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" type="text" name="name" id="name" value="{{ old('name', $kindergardenBranch->name) }}" required>
                @if($errors->has('name'))
                    <div class="invalid-feedback">
                        {{ $errors->first('name') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.kindergardenBranch.fields.name_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="address">{{ trans('cruds.kindergardenBranch.fields.address') }}</label>
                <input class="form-control {{ $errors->has('address') ? 'is-invalid' : '' }}" type="text" name="address" id="address" value="{{ old('address', $kindergardenBranch->address) }}" required>
                @if($errors->has('address'))
                    <div class="invalid-feedback">
                        {{ $errors->first('address') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.kindergardenBranch.fields.address_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="branch_manager">{{ trans('cruds.kindergardenBranch.fields.branch_manager') }}</label>
                <input class="form-control {{ $errors->has('branch_manager') ? 'is-invalid' : '' }}" type="text" name="branch_manager" id="branch_manager" value="{{ old('branch_manager', $kindergardenBranch->branch_manager) }}" required>
                @if($errors->has('branch_manager'))
                    <div class="invalid-feedback">
                        {{ $errors->first('branch_manager') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.kindergardenBranch.fields.branch_manager_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="phone">{{ trans('cruds.kindergardenBranch.fields.email') }}</label>
                <input class="form-control {{ $errors->has('email') ? 'is-invalid' : '' }}" type="email" name="email" id="email" value="{{ old('email', $kindergardenBranch->email) }}">
                @if($errors->has('email'))
                    <div class="invalid-feedback">
                        {{ $errors->first('email') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.kindergardenBranch.fields.email_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="phone">{{ trans('cruds.kindergardenBranch.fields.phone') }}</label>
                <input class="form-control {{ $errors->has('phone') ? 'is-invalid' : '' }}" type="number" name="phone" id="phone" value="{{ old('phone', $kindergardenBranch->phone) }}" step="1">
                @if($errors->has('phone'))
                    <div class="invalid-feedback">
                        {{ $errors->first('phone') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.kindergardenBranch.fields.phone_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/kindergardenBranches/index.blade.php
@extends('layouts.admin')
@section('content')
@can('kindergarden_branch_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route('admin.kindergarden-branches.create') }}">
                {{ trans('global.add') }} {{ trans('cruds.kindergardenBranch.title_singular') }}
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('cruds.kindergardenBranch.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-KindergardenBranch">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.kindergardenBranch.fields.id') }}
                        </th>
                        <th>
                            {{ trans('cruds.kindergardenBranch.fields.name') }}
                        </th>
                        <th>
                            {{ trans('cruds.kindergardenBranch.fields.address') }}
                        </th>
                        <th>
                            {{ trans('cruds.kindergardenBranch.fields.branch_manager') }}
                        </th>
                        <th>
                            {{ trans('cruds.kindergardenBranch.fields.email') }}
                        </th>
                        <th>
                            {{ trans('cruds.kindergardenBranch.fields.phone') }}
                        </th>
                        <th>
                            {{ trans('cruds.kindergardenBranch.fields.phone') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($kindergardenBranches as $key => $kindergardenBranch)
                        <tr data-entry-id="{{ $kindergardenBranch->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $kindergardenBranch->id ?? '' }}
                            </td>
                            <td>
                                {{ $kindergardenBranch->name ?? '' }}
                            </td>
                            <td>
                                {{ $kindergardenBranch->address ?? '' }}
                            </td>
                            <td>
                                {{ $kindergardenBranch->branch_manager ?? '' }}
                            </td>
                            <td>
                                {{ $kindergardenBranch->email ?? '' }}
                            </td>
                            <td>
                                {{ $kindergardenBranch->phone ?? '' }}
                            </td>
                            <td>
                                @can('kindergarden_branch_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.kindergarden-branches.show', $kindergardenBranch->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan

                                @can('kindergarden_branch_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.kindergarden-branches.edit', $kindergardenBranch->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan

                                @can('kindergarden_branch_delete')
                                    <form action="{{ route('admin.kindergarden-branches.destroy', $kindergardenBranch->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan

                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>



@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('kindergarden_branch_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.kindergarden-branches.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    orderCellsTop: true,
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  let table = $('.datatable-KindergardenBranch:not(.ajaxTable)').DataTable({ buttons: dtButtons })
  $('a[data-toggle="tab"]').on('shown.bs.tab click', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
          .columns.adjust();
  });

})

</script>
@endsection

resources/views/admin/kindergardenBranches/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('cruds.kindergardenBranch.title') }}
    </div>

    <div class="card-body">
        <div class="form-group">
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.kindergarden-branches.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>
                            {{ trans('cruds.kindergardenBranch.fields.id') }}
                        </th>
                        <td>
                            {{ $kindergardenBranch->id }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.kindergardenBranch.fields.name') }}
                        </th>
                        <td>
                            {{ $kindergardenBranch->name }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.kindergardenBranch.fields.address') }}
                        </th>
                        <td>
                            {{ $kindergardenBranch->address }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.kindergardenBranch.fields.branch_manager') }}
                        </th>
                        <td>
                            {{ $kindergardenBranch->branch_manager }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.kindergardenBranch.fields.email') }}
                        </th>
                        <td>
                            {{ $kindergardenBranch->email }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.kindergardenBranch.fields.phone') }}
                        </th>
                        <td>
                            {{ $kindergardenBranch->phone }}
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.kindergarden-branches.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
        </div>
    </div>
</div>

<div class="card">
    <div class="card-header">
        {{ trans('global.relatedData') }}
    </div>
    <ul class="nav nav-tabs" role="tablist" id="relationship-tabs">
        <li class="nav-item">
            <a class="nav-link" href="#kindergarden_branch_kindergarden_groups" role="tab" data-toggle="tab">
                {{ trans('cruds.kindergardenGroup.title') }}
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#branch_kids" role="tab" data-toggle="tab">
                {{ trans('cruds.kid.title') }}
            </a>
        </li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane" role="tabpanel" id="kindergarden_branch_kindergarden_groups">
            @includeIf('admin.kindergardenBranches.relationships.kindergardenBranchKindergardenGroups', ['kindergardenGroups' => $kindergardenBranch->kindergardenBranchKindergardenGroups])
        </div>
        <div class="tab-pane" role="tabpanel" id="branch_kids">
            @includeIf('admin.kindergardenBranches.relationships.branchKids', ['kids' => $kindergardenBranch->branchKids])
        </div>
    </div>
</div>

@endsection