routes/web.php
<?php

use App\Models\Index;

//Route::redirect('/admin', '/login');
Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }
    return redirect()->route('admin.home');
});

Auth::routes(["register" => false]);

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/index', 'SettingsController@index_edit')->name('settings.index');
    Route::put('/index', 'SettingsController@index_update')->name('settings.index.update');

    Route::get('/mails', 'MailController@index')->name('mail.index');
    Route::get('/mails/{receivedMail}', 'MailController@show')->name('mail.show');

    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Crm Status
    Route::delete('crm-statuses/destroy', 'CrmStatusController@massDestroy')->name('crm-statuses.massDestroy');
    Route::resource('crm-statuses', 'CrmStatusController');

    // Crm Customer
    Route::delete('crm-customers/destroy', 'CrmCustomerController@massDestroy')->name('crm-customers.massDestroy');
    Route::resource('crm-customers', 'CrmCustomerController');

    // Crm Note
    Route::delete('crm-notes/destroy', 'CrmNoteController@massDestroy')->name('crm-notes.massDestroy');
    Route::resource('crm-notes', 'CrmNoteController');

    // Crm Document
    Route::delete('crm-documents/destroy', 'CrmDocumentController@massDestroy')->name('crm-documents.massDestroy');
    Route::post('crm-documents/media', 'CrmDocumentController@storeMedia')->name('crm-documents.storeMedia');
    Route::post('crm-documents/ckmedia', 'CrmDocumentController@storeCKEditorImages')->name('crm-documents.storeCKEditorImages');
    Route::resource('crm-documents', 'CrmDocumentController');

    // Kindergarden Branch
    Route::delete('kindergarden-branches/destroy', 'KindergardenBranchController@massDestroy')->name('kindergarden-branches.massDestroy');
    Route::resource('kindergarden-branches', 'KindergardenBranchController');

    // Kindergarden Group
    Route::delete('kindergarden-groups/destroy', 'KindergardenGroupController@massDestroy')->name('kindergarden-groups.massDestroy');
    Route::resource('kindergarden-groups', 'KindergardenGroupController');

    // Kid
    Route::post('/exportKids', 'KidController@export')->name('exportKids');
    Route::post('/exportKidsByGroup', 'KidController@exportKidsByGroup')->name('exportKidsByGroup');
    Route::delete('kids/destroy', 'KidController@massDestroy')->name('kids.massDestroy');
    Route::resource('kids', 'KidController');
    // Parent Guardian
    Route::delete('parent-guardians/destroy', 'ParentGuardianController@massDestroy')->name('parent-guardians.massDestroy');
    Route::resource('parent-guardians', 'ParentGuardianController');
    Route::resource('kid-categories', 'kidCategoriesController');
});
Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
    // Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
        Route::post('profile', 'ChangePasswordController@updateProfile')->name('password.updateProfile');
        Route::post('profile/destroy', 'ChangePasswordController@destroy')->name('password.destroyProfile');
    }
});
Route::middleware(['web'])->group(function () {
    Route::get('/', function () {
        return view('front.layouts.main');
    });
    Route::get('/home', function(){
        $index = Index::first();
        return view('front.home', compact('index'));
    });
    Route::get('/register', function(){
        return view('front.pages.register');
    });
    Route::get('/contact', function(){
        return view('front.pages.contact');
    });
    Route::get('/about', function(){
        return view('front.pages.about');
    });
    Route::get('/check-if-registered', function(){
        return view('front.pages.checkIfResgistered');
    });
    Route::post('/register', 'Front\RegisterController@register')->name('register');
    Route::post('/getBranches', 'Front\RegisterController@getBranches')->name('getBranches');
    Route::post('/getKidCategories', 'Front\RegisterController@getKidCategories')->name('getKidCategories');
    Route::post('/getKidNationalities', 'Front\RegisterController@getKidNationalities')->name('getKidNationalities');
    Route::post('/getBranchGroups', 'Front\RegisterController@getBranchGroups')->name('getBranchGroups');
    Route::post('/checking-if-registered', 'Front\RegisterController@checkIfRegistered')->name('checkIfRegistered');
    Route::post('/get-branches', 'Front\RegisterController@retrieveBranchesWithGroups')->name('retrieveBranchesWithGroups');

    Route::post('/contect', 'ContactFormController@send')->name('contact.send');
});

app/Models/ParentGuardian.php
<?php

namespace App\Models;

use \DateTimeInterface;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class ParentGuardian extends Model
{
    use SoftDeletes;
    use HasFactory;

    public $table = 'parent_guardians';

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $guarded = ['id'];

    public function parentGuardianKids()
    {
        return $this->hasMany(Kid::class, 'parent_guardian_id', 'id');
    }

    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }
}

app/Http/Controllers/Admin/ParentGuardianController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyParentGuardianRequest;
use App\Http\Requests\StoreParentGuardianRequest;
use App\Http\Requests\UpdateParentGuardianRequest;
use App\Models\ParentGuardian;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class ParentGuardianController extends Controller
{
    public function index()
    {
        abort_if(Gate::denies('parent_guardian_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $parentGuardians = ParentGuardian::all();

        return view('admin.parentGuardians.index', compact('parentGuardians'));
    }

    public function create()
    {
        abort_if(Gate::denies('parent_guardian_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.parentGuardians.create');
    }

    public function store(StoreParentGuardianRequest $request)
    {
        $parentGuardian = ParentGuardian::create($request->all());

        return redirect()->route('admin.parent-guardians.index');
    }

    public function edit(ParentGuardian $parentGuardian)
    {
        abort_if(Gate::denies('parent_guardian_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.parentGuardians.edit', compact('parentGuardian'));
    }

    public function update(UpdateParentGuardianRequest $request, ParentGuardian $parentGuardian)
    {
        $parentGuardian->update($request->all());

        return redirect()->route('admin.parent-guardians.index');
    }

    public function show(ParentGuardian $parentGuardian)
    {
        abort_if(Gate::denies('parent_guardian_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $parentGuardian->load('parentGuardianKids');

        return view('admin.parentGuardians.show', compact('parentGuardian'));
    }

    public function destroy(ParentGuardian $parentGuardian)
    {
        abort_if(Gate::denies('parent_guardian_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $parentGuardian->delete();

        return back();
    }

    public function massDestroy(MassDestroyParentGuardianRequest $request)
    {
        ParentGuardian::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

resources/views/admin/parentGuardians/relationships/parentGuardianKids.blade.php
@can('kid_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route('admin.kids.create') }}">
                {{ trans('global.add') }} {{ trans('cruds.kid.title_singular') }}
            </a>
        </div>
    </div>
@endcan

<div class="card">
    <div class="card-header">
        {{ trans('cruds.kid.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-parentGuardianKids">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.kid.fields.id') }}
                        </th>
                        <th>
                            {{ trans('cruds.kid.fields.name') }}
                        </th>
                        <th>
                            {{ trans('cruds.kid.fields.lastname') }}
                        </th>
                        <th>
                            {{ trans('cruds.kid.fields.id_number') }}
                        </th>
                        <th>
                            {{ trans('cruds.kid.fields.date_of_birth') }}
                        </th>
                        <th>
                            {{ trans('cruds.kid.fields.branch') }}
                        </th>
                        <th>
                            {{ trans('cruds.kid.fields.group') }}
                        </th>
                        <th>
                            {{ trans('cruds.kindergardenGroup.fields.vacancy') }}
                        </th>
                        <th>
                            {{ trans('cruds.kid.fields.parent_guardian') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($kids as $key => $kid)
                        <tr data-entry-id="{{ $kid->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $kid->id ?? '' }}
                            </td>
                            <td>
                                {{ $kid->name ?? '' }}
                            </td>
                            <td>
                                {{ $kid->lastname ?? '' }}
                            </td>
                            <td>
                                {{ $kid->id_number ?? '' }}
                            </td>
                            <td>
                                {{ $kid->date_of_birth ?? '' }}
                            </td>
                            <td>
                                {{ $kid->branch->name ?? '' }}
                            </td>
                            <td>
                                {{ $kid->group->name ?? '' }}
                            </td>
                            <td>
                                {{ $kid->group->vacancy ?? '' }}
                            </td>
                            <td>
                                {{ $kid->parent_guardian->guardian_type ?? '' }}
                            </td>
                            <td>
                                @can('kid_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.kids.show', $kid->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan

                                @can('kid_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.kids.edit', $kid->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan

                                @can('kid_delete')
                                    <form action="{{ route('admin.kids.destroy', $kid->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan

                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>

@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('kid_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.kids.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    orderCellsTop: true,
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  let table = $('.datatable-parentGuardianKids:not(.ajaxTable)').DataTable({ buttons: dtButtons })
  $('a[data-toggle="tab"]').on('shown.bs.tab click', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
          .columns.adjust();
  });
  
})

</script>
@endsection