routes/web.php
<?php

use App\Models\Index;

//Route::redirect('/admin', '/login');
Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }
    return redirect()->route('admin.home');
});

Auth::routes(["register" => false]);

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/index', 'SettingsController@index_edit')->name('settings.index');
    Route::put('/index', 'SettingsController@index_update')->name('settings.index.update');

    Route::get('/mails', 'MailController@index')->name('mail.index');
    Route::get('/mails/{receivedMail}', 'MailController@show')->name('mail.show');

    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Crm Status
    Route::delete('crm-statuses/destroy', 'CrmStatusController@massDestroy')->name('crm-statuses.massDestroy');
    Route::resource('crm-statuses', 'CrmStatusController');

    // Crm Customer
    Route::delete('crm-customers/destroy', 'CrmCustomerController@massDestroy')->name('crm-customers.massDestroy');
    Route::resource('crm-customers', 'CrmCustomerController');

    // Crm Note
    Route::delete('crm-notes/destroy', 'CrmNoteController@massDestroy')->name('crm-notes.massDestroy');
    Route::resource('crm-notes', 'CrmNoteController');

    // Crm Document
    Route::delete('crm-documents/destroy', 'CrmDocumentController@massDestroy')->name('crm-documents.massDestroy');
    Route::post('crm-documents/media', 'CrmDocumentController@storeMedia')->name('crm-documents.storeMedia');
    Route::post('crm-documents/ckmedia', 'CrmDocumentController@storeCKEditorImages')->name('crm-documents.storeCKEditorImages');
    Route::resource('crm-documents', 'CrmDocumentController');

    // Kindergarden Branch
    Route::delete('kindergarden-branches/destroy', 'KindergardenBranchController@massDestroy')->name('kindergarden-branches.massDestroy');
    Route::resource('kindergarden-branches', 'KindergardenBranchController');

    // Kindergarden Group
    Route::delete('kindergarden-groups/destroy', 'KindergardenGroupController@massDestroy')->name('kindergarden-groups.massDestroy');
    Route::resource('kindergarden-groups', 'KindergardenGroupController');

    // Kid
    Route::post('/exportKids', 'KidController@export')->name('exportKids');
    Route::post('/exportKidsByGroup', 'KidController@exportKidsByGroup')->name('exportKidsByGroup');
    Route::delete('kids/destroy', 'KidController@massDestroy')->name('kids.massDestroy');
    Route::resource('kids', 'KidController');
    // Parent Guardian
    Route::delete('parent-guardians/destroy', 'ParentGuardianController@massDestroy')->name('parent-guardians.massDestroy');
    Route::resource('parent-guardians', 'ParentGuardianController');
    Route::resource('kid-categories', 'kidCategoriesController');
});
Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
    // Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
        Route::post('profile', 'ChangePasswordController@updateProfile')->name('password.updateProfile');
        Route::post('profile/destroy', 'ChangePasswordController@destroy')->name('password.destroyProfile');
    }
});
Route::middleware(['web'])->group(function () {
    Route::get('/', function () {
        return view('front.layouts.main');
    });
    Route::get('/home', function(){
        $index = Index::first();
        return view('front.home', compact('index'));
    });
    Route::get('/register', function(){
        return view('front.pages.register');
    });
    Route::get('/contact', function(){
        return view('front.pages.contact');
    });
    Route::get('/about', function(){
        return view('front.pages.about');
    });
    Route::get('/check-if-registered', function(){
        return view('front.pages.checkIfResgistered');
    });
    Route::post('/register', 'Front\RegisterController@register')->name('register');
    Route::post('/getBranches', 'Front\RegisterController@getBranches')->name('getBranches');
    Route::post('/getKidCategories', 'Front\RegisterController@getKidCategories')->name('getKidCategories');
    Route::post('/getKidNationalities', 'Front\RegisterController@getKidNationalities')->name('getKidNationalities');
    Route::post('/getBranchGroups', 'Front\RegisterController@getBranchGroups')->name('getBranchGroups');
    Route::post('/checking-if-registered', 'Front\RegisterController@checkIfRegistered')->name('checkIfRegistered');
    Route::post('/get-branches', 'Front\RegisterController@retrieveBranchesWithGroups')->name('retrieveBranchesWithGroups');

    Route::post('/contect', 'ContactFormController@send')->name('contact.send');
});

app/Models/KindergardenGroup.php
<?php

namespace App\Models;

use \DateTimeInterface;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class KindergardenGroup extends Model
{
    use SoftDeletes;
    use HasFactory;

    public $table = 'kindergarden_groups';

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'name',
        'vacancy',
        'kindergarden_branch_id',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    public function groupKids()
    {
        return $this->hasMany(Kid::class, 'group_id', 'id');
    }

    public function addonGroupKids()
    {
        return $this->hasMany(Kid::class, 'group_id', 'id');
    }

    public function kindergarden_branch()
    {
        return $this->belongsTo(KindergardenBranch::class, 'kindergarden_branch_id');
    }

    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }
}

app/Http/Controllers/Admin/KindergardenGroupController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyKindergardenGroupRequest;
use App\Http\Requests\StoreKindergardenGroupRequest;
use App\Http\Requests\UpdateKindergardenGroupRequest;
use App\Models\KindergardenBranch;
use App\Models\KindergardenGroup;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class KindergardenGroupController extends Controller
{
    public function index()
    {
        abort_if(Gate::denies('kindergarden_group_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $kindergardenGroups = KindergardenGroup::with(['kindergarden_branch'])->get();

        return view('admin.kindergardenGroups.index', compact('kindergardenGroups'));
    }

    public function create()
    {
        abort_if(Gate::denies('kindergarden_group_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $kindergarden_branches = KindergardenBranch::pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        return view('admin.kindergardenGroups.create', compact('kindergarden_branches'));
    }

    public function store(StoreKindergardenGroupRequest $request)
    {
        $kindergardenGroup = KindergardenGroup::create($request->all());

        return redirect()->route('admin.kindergarden-groups.index');
    }

    public function edit(KindergardenGroup $kindergardenGroup)
    {
        abort_if(Gate::denies('kindergarden_group_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $kindergarden_branches = KindergardenBranch::pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        $kindergardenGroup->load('kindergarden_branch');

        return view('admin.kindergardenGroups.edit', compact('kindergardenGroup', 'kindergarden_branches'));
    }

    public function update(UpdateKindergardenGroupRequest $request, KindergardenGroup $kindergardenGroup)
    {
        $kindergardenGroup->update($request->all());

        return redirect()->route('admin.kindergarden-groups.index');
    }

    public function show(KindergardenGroup $kindergardenGroup)
    {
        abort_if(Gate::denies('kindergarden_group_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $kindergardenGroup->load('kindergarden_branch', 'groupKids');

        return view('admin.kindergardenGroups.show', compact('kindergardenGroup'));
    }

    public function destroy(KindergardenGroup $kindergardenGroup)
    {
        abort_if(Gate::denies('kindergarden_group_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $kindergardenGroup->delete();

        return back();
    }

    public function massDestroy(MassDestroyKindergardenGroupRequest $request)
    {
        KindergardenGroup::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

resources/views/admin/kindergardenGroups/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.kindergardenGroup.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.kindergarden-groups.store") }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label class="required" for="name">{{ trans('cruds.kindergardenGroup.fields.name') }}</label>
                <input class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" type="text" name="name" id="name" value="{{ old('name', '') }}" required>
                @if($errors->has('name'))
                    <div class="invalid-feedback">
                        {{ $errors->first('name') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.kindergardenGroup.fields.name_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="vacancy">{{ trans('cruds.kindergardenGroup.fields.vacancy') }}</label>
                <input class="form-control {{ $errors->has('vacancy') ? 'is-invalid' : '' }}" type="number" name="vacancy" id="vacancy" value="{{ old('vacancy', '') }}" step="1" required>
                @if($errors->has('vacancy'))
                    <div class="invalid-feedback">
                        {{ $errors->first('vacancy') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.kindergardenGroup.fields.vacancy_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="kindergarden_branch_id">{{ trans('cruds.kindergardenGroup.fields.kindergarden_branch') }}</label>
                <select class="form-control select2 {{ $errors->has('kindergarden_branch') ? 'is-invalid' : '' }}" name="kindergarden_branch_id" id="kindergarden_branch_id" required>
                    @foreach($kindergarden_branches as $id => $entry)
                        <option value="{{ $id }}" {{ old('kindergarden_branch_id') == $id ? 'selected' : '' }}>{{ $entry }}</option>
                    @endforeach
                </select>
                @if($errors->has('kindergarden_branch'))
                    <div class="invalid-feedback">
                        {{ $errors->first('kindergarden_branch') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.kindergardenGroup.fields.kindergarden_branch_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/kindergardenGroups/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('cruds.kindergardenGroup.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.kindergarden-groups.update", [$kindergardenGroup->id]) }}" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label class="required" for="name">{{ trans('cruds.kindergardenGroup.fields.name') }}</label>
                <input class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" type="text" name="name" id="name" value="{{ old('name', $kindergardenGroup->name) }}" required>
                @if($errors->has('name'))
                    <div class="invalid-feedback">
                        {{ $errors->first('name') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.kindergardenGroup.fields.name_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="vacancy">{{ trans('cruds.kindergardenGroup.fields.vacancy') }}</label>
                <input class="form-control {{ $errors->has('vacancy') ? 'is-invalid' : '' }}" type="number" name="vacancy" id="vacancy" value="{{ old('vacancy', $kindergardenGroup->vacancy) }}" step="1" required>
                @if($errors->has('vacancy'))
                    <div class="invalid-feedback">
                        {{ $errors->first('vacancy') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.kindergardenGroup.fields.vacancy_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="kindergarden_branch_id">{{ trans('cruds.kindergardenGroup.fields.kindergarden_branch') }}</label>
                <select class="form-control select2 {{ $errors->has('kindergarden_branch') ? 'is-invalid' : '' }}" name="kindergarden_branch_id" id="kindergarden_branch_id" required>
                    @foreach($kindergarden_branches as $id => $entry)
                        <option value="{{ $id }}" {{ (old('kindergarden_branch_id') ? old('kindergarden_branch_id') : $kindergardenGroup->kindergarden_branch->id ?? '') == $id ? 'selected' : '' }}>{{ $entry }}</option>
                    @endforeach
                </select>
                @if($errors->has('kindergarden_branch'))
                    <div class="invalid-feedback">
                        {{ $errors->first('kindergarden_branch') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.kindergardenGroup.fields.kindergarden_branch_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/kindergardenGroups/index.blade.php
@extends('layouts.admin')
@section('content')
@can('kindergarden_group_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route('admin.kindergarden-groups.create') }}">
                {{ trans('global.add') }} {{ trans('cruds.kindergardenGroup.title_singular') }}
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('cruds.kindergardenGroup.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-KindergardenGroup">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.kindergardenGroup.fields.id') }}
                        </th>
                        <th>
                            {{ trans('cruds.kindergardenGroup.fields.name') }}
                        </th>
                        <th>
                            {{ trans('cruds.kindergardenGroup.fields.vacancy') }}
                        </th>
                        <th>
                            {{ trans('cruds.kindergardenGroup.fields.kindergarden_branch') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($kindergardenGroups as $key => $kindergardenGroup)
                        <tr data-entry-id="{{ $kindergardenGroup->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $loop->iteration ?? '' }}
                            </td>
                            <td>
                                {{ $kindergardenGroup->name ?? '' }}
                            </td>
                            <td>
                                {{ $kindergardenGroup->vacancy ?? '' }}
                            </td>
                            <td>
                                {{ $kindergardenGroup->kindergarden_branch->name ?? '' }}
                            </td>
                            <td>
                                @can('kindergarden_group_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.kindergarden-groups.show', $kindergardenGroup->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan

                                @can('kindergarden_group_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.kindergarden-groups.edit', $kindergardenGroup->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan

                                @can('kindergarden_group_delete')
                                    <form action="{{ route('admin.kindergarden-groups.destroy', $kindergardenGroup->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan

                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>



@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('kindergarden_group_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.kindergarden-groups.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    orderCellsTop: true,
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  let table = $('.datatable-KindergardenGroup:not(.ajaxTable)').DataTable({ buttons: dtButtons })
  $('a[data-toggle="tab"]').on('shown.bs.tab click', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
          .columns.adjust();
  });
  
})

</script>
@endsection

resources/views/admin/kindergardenGroups/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('cruds.kindergardenGroup.title') }}
    </div>

    <div class="card-body">
        <div class="form-group">
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.kindergarden-groups.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>
                            {{ trans('cruds.kindergardenGroup.fields.id') }}
                        </th>
                        <td>
                            {{ $kindergardenGroup->id }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.kindergardenGroup.fields.name') }}
                        </th>
                        <td>
                            {{ $kindergardenGroup->name }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.kindergardenGroup.fields.vacancy') }}
                        </th>
                        <td>
                            {{ $kindergardenGroup->vacancy }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.kindergardenGroup.fields.kindergarden_branch') }}
                        </th>
                        <td>
                            {{ $kindergardenGroup->kindergarden_branch->name ?? '' }}
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.kindergarden-groups.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
        </div>
    </div>
</div>

<div class="card">
    <div class="card-header">
        {{ trans('global.relatedData') }}
    </div>
    <ul class="nav nav-tabs" role="tablist" id="relationship-tabs">
        <li class="nav-item">
            <a class="nav-link" href="#group_kids" role="tab" data-toggle="tab">
                {{ trans('cruds.kid.title') }}
            </a>
        </li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane" role="tabpanel" id="group_kids">
            @includeIf('admin.kindergardenGroups.relationships.groupKids', ['kids' => $kindergardenGroup->groupKids()->orderBy('addon_group_id', 'asc')->orderBy('created_at', 'desc')->get()])
        </div>
    </div>
</div>

@endsection